spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/juju_market
    username: root
    password: juju
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
