spring:
  datasource:
    url: jdbc:postgresql://${SQL_URL:localhost}/juju_market
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:juju}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
