CREATE TABLE tb_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_name VARCHAR(255),
   measurement_unit VARCHAR(255),
   unit_price DECIMAL(6, 2),
   category_id BIGINT,
   CONSTRAINT pk_tb_product PRIMARY KEY (id)
);
