CREATE TABLE tb_payment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   payment_method VARCHAR(255),
   payment_date TIMESTAMP WITHOUT TIME ZONE,
   final_price DECIMAL(6, 2),
   CONSTRAINT pk_tb_payment PRIMARY KEY (id)
);
