CREATE TABLE tb_product_cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id BIGINT,
   quantity INTEGER,
   acquisition_price DECIMAL(20, 2),
   cart_id BIGINT,
   CONSTRAINT pk_tb_product_cart PRIMARY KEY (id)
);
